# Generated by Django 2.2.10 on 2021-07-14 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, max_length=250, null=True)),
                ('poskod', models.CharField(blank=True, max_length=5, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthday', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tollfree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdatetime', models.CharField(max_length=50, verbose_name='Start DateTime')),
                ('tollfree', models.CharField(max_length=12)),
                ('answerpoint', models.CharField(max_length=15)),
                ('customer_name', models.CharField(max_length=50)),
                ('account_num', models.CharField(max_length=20, verbose_name='Account Num')),
                ('caller', models.CharField(max_length=15)),
                ('call_date', models.CharField(max_length=30)),
                ('call_time', models.CharField(max_length=20)),
                ('hr', models.CharField(max_length=50)),
                ('dy', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('calls', models.IntegerField()),
                ('callsless60sec', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('dduration', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('busy', models.IntegerField()),
                ('no_answer', models.IntegerField()),
                ('other', models.IntegerField()),
                ('incomplete', models.IntegerField()),
                ('complete', models.IntegerField()),
                ('dur_range', models.CharField(max_length=50)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('hr_id', models.IntegerField()),
                ('state_id', models.IntegerField()),
                ('dur_range_id', models.IntegerField()),
                ('billing', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compName', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
