# Generated by Django 2.2.10 on 2021-07-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='poskod',
            new_name='poscode',
        ),
    ]
